CC = g++



# Compiler flags

CFLAGS = -Wall -Wextra -std=c++11 -fopenmp



# Source files

SRCS = Q2.cpp



# Executable name

TARGET = myprogram



all: $(TARGET)



$(TARGET): $(SRCS)

	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)



clean:

	rm -f $(TARGET)
